### ISSUE TITLE
[Info] Add version number for QDockX

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QDNH#1]
Add version number in Name of Release (-package)

p.s. Version number is now (only) visuable when starting App and go2 Setting

![Knipsel](https://github.com/nicsure/QDNH/assets/148579604/3f9a94d7-32f1-48a3-9915-1485b7bdbaec)

**Comment by nicsure** [comment]
It'll have to do, messing with meta data in MAUI can cause a bunch of trouble as the compiler and environment is so fragile and buggy to changes like that. I changed a single property setting in the project and it took me hours to recover back to a state where I could compile successfully again. I ain't touching it again.

**Comment by ErikS-web** [comment]
oeps OK as is work fine !
